# Generated by Django 5.1.1 on 2025-02-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
