# Generated by Django 5.1.1 on 2025-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_jobs_job_rename_notifications_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='activity',
            name='meta_ai',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='activity',
            name='meta_human',
            field=models.JSONField(default=dict),
        ),
    ]
