# Generated by Django 5.1.1 on 2025-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_activity_meta_data_activity_meta_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
