# Generated by Django 5.1.1 on 2025-02-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_activity_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.TextField(),
        ),
    ]
