# Generated by Django 5.1.1 on 2025-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_activity_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='meta_human',
        ),
        migrations.AlterField(
            model_name='activity',
            name='field',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
